version: '3'

volumes:
  jtket_db_data:
services:
  db:
    restart: always
    image: postgres:16
    container_name: jtket__service_db
    ports:
      - 54325:5432
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - jtket_db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: core
      POSTGRES_PASSWORD: password
      APP_DB_NAMES: 'jtket'
      APP_DB_USER: jtket_user
      APP_DB_PASS: jtket_pass
      APP_DB_SCHEMAS: jtket
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5